# Generated by Django 3.0.5 on 2020-12-16 13:29

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_interior', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interior',
            name='message',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='interior',
            name='phoneno',
            field=phone_field.models.PhoneField(blank=True, default=True, max_length=31),
        ),
    ]
